server:
  port: 8031

spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8030
      acks: all
    topic-name: avro-demo-topic

logging:
  level:
    org.apache.kafka: INFO
    io.confluent: INFO
    io.confluent.kafka.serializers: ERROR
    org.apache.kafka.clients.producer: ERROR