server:
  port: 8032

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      bootstrap-servers: localhost:29092
      group-id: avro-demo-group
      auto-offset-reset: earliest
      properties:
        schema.registry.url: http://localhost:8030
        specific.avro.reader: true
    topic-name: avro-demo-topic
    listener:
      concurrency: 3

logging:
  level:
    org.apache.kafka: INFO
    io.confluent: INFO
    org.apache.kafka.clients.consumer: ERROR
    io.confluent.kafka.serializers.KafkaAvroDeserializerConfig: ERROR
